# Generated by Django 4.2 on 2023-04-24 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="assigned",
            new_name="assignee",
        ),
    ]
