# Generated by Django 4.2 on 2023-04-26 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_is_active_task_is_deleted_task_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
    ]
