# Generated by Django 4.2 on 2023-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tasks",
            "0004_remove_task_is_active_remove_task_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="color",
            field=models.CharField(default="green", max_length=7),
        ),
    ]
