# Generated by Django 4.2 on 2023-04-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_task_due_date_alter_task_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="notes",
        ),
        migrations.CreateModel(
            name="TaskNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(default="none")),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.task",
                    ),
                ),
            ],
        ),
    ]
